os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: C:\gopath\src\github.com\tao-foundation\open-teo-pool
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GOPATH: C:\gopath
    CC: gcc.exe
  matrix:
    - TEO_ARCH: amd64
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.11.1.windows-%TEO_ARCH%.zip
  - 7z x go1.11.1.windows-%TEO_ARCH%.zip -y -oC:\ > NUL
  - go version
  - gcc --version

build_script:
  - go get -v ./...
